# Plugins
gems:
  - jekyll-sitemap
  - nokogiri
  - text-hyphen
safe: false

# Build Settings
markdown: kramdown
exclude: 
  - automation/
  - README.md
  - LICENSE.txt
  - script/
  - _stuff/
  - external/
  - Gemfile
  - Gemfile.lock
  - tmp/

sass:
  style: :compressed

sitemap:
  extensions:
    - .tgz

# Site and <head> Settings
author: "Eurac Research & cmc-corpora"
description: "5th Conference on CMC and Social Media Corpora for the Humanities (3-4 Oct 2017) and CLARIN UI Event (4 Oct 2017) @ Eurac Research, IT"
shortDescription: "5th cmc-corpora conference and CLARIN UI Event(3-4Oct17) @ Eurac Research, IT"
metaKeywords: "CMC, Social Media, Corpora, Humanities, Conference, Eurac Research, Bolzano, Bozen, CLARIN, UI Event"
title: "CMC-Corpora 2017 Conference and CLARIN UI Event"
email: "cmc-corpora2017@eurac.edu"
baseurl: ""
url: "https://cmc-corpora2017.eurac.edu"
permalink: "/blog/:year:month:day_:title/"
analytics:
  - name: "piwik"
googleSiteVerification: ""
googleMapsApiKey: "AIzaSyB6hiwDZTjA2YMPP8xyCRJN4JCZW79lt7E"

twitterAccount: "@cmc_corpora"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
# socialImageSrcFacebook: "/img/seo/sharing-facebook.png"
faviconVersion: 2

# Organizer Info
organizerName: "ISCM@EURAC"
organizerAlternateName: "Institute for Specialised Communication and Multilingualism"
organizerDescription: "Scientific answers to current issues of language and education policy as well as to economic and social questions for South Tyrol and beyond."
organizerEmail: "cmc-corpora2017@eurac.edu"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.eurac.edu/iscm"


# Documents
#c4pUrl: "https://bit.ly/dfua-c4p"
#c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/cfp/", text: "CFP (Monograph)"}
 - {permalink: "/proceedings/", text: "Proceedings"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/uievent/", text: "CLARIN UI Event"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/committees/", text: "Committees"}
 - {permalink: "/blog/", text: "News"}
bottomNavigationLinks:
  - {link: "http://cmc-corpora.org", text: "cmc-corpora"}
rightNavigationButtons:
  - {link: "http://cmc-corpora.org", text: "cmc-corpora"}

# Hero Block
# heroImage: "hero.jpg"
heroTitle: "CMC-Corpora 2017 <typeout>"
eventDate: "October, 3-4th 2017"
typeoutTextValues: '"", " in Bolzano/Bozen", " in South Tyrol", " in Italy", " @ Eurac Research"'
typeoutFallback: " @ Eurac Research"
heroButtons:
    - {permalink: "cfp", text: "Call for Papers (Monograph)"}
    - {permalink: "proceedings", text: "Proceedings Online"}
    - {permalink: "twitter-moment", text: "Twitter Moment"}
    # - {permalink: "registration", text: "Registration"}
    # - {permalink: "uievent", text: "CLARIN UI Event"}

# About Block
aboutTitle: "About"
aboutBlock:
 - {title: "Conference", image: "conference.png", text: '
   <p>CMC and Social Media Corpora for the Humanities is the 5th edition of an annual <a href="https://sites.google.com/site/cmccorpora/conferences-2013-2016" target="_blank">conference series</a> dedicated to the collection, annotation, processing and exploitation of corpora of computer-mediated communication (CMC) and social media for research in the humanities. The conference brings together language-centered research on CMC and social media in linguistics, philologies, communication sciences, media and social sciences with research questions from the fields of corpus and computational linguistics, language technology, text technology, and machine learning.</p>
   <p>The conference will include a <a href="/uievent">post-conference workshop</a> on using the TEI for annotating CMC and social media resources (4 October).
   The conference will be followed by the <a href="http://lcr2017.eurac.edu" target="_blank">4th Learner Corpus Research Conference</a> and its preceding conference workshop, which will both be held at the same venue from 4-7 October.</p>
   ' }
 - {title: "Eurac Research", image: "eurac.jpg", text: '
   <p>The Institute for Specialised Communication and Multilingualism aims to provide scientific answers to current issues of language and education policy as well as to economic and social questions at local and international level.</p>
   <p>It is part of <a href="http://www.eurac.edu" target="_blank">Eurac Research</a>, an innovative centre for research and training based in South Tyrol, Italy. This private research centre founded in 1992 today hosts an international community of researchers. Interdisciplinary teams conduct research in four main subject areas: autonomies, health, mountains and technologies.</p>
   ' }

   ## Statistic Block
   #statisticBlockImage: "statistic.jpg"
   #statisticBlock:
   # - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
   # - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
   # - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
   # - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 2
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Eurac Research"
eventLocationLink: "http://www.eurac.edu/"
eventStreetAddress: "Viale Druso, 1 / Drususallee 1"
eventAddressLocality: "Bolzano / Bozen"
eventAddressLocalityRegion: "Trentino-Alto Adige / Südtirol"
eventPostalCode: "39100"
eventAddressCountry: "Italy"
eventStartTime: "2017-10-03T10:00"
eventDoorTime: "09:00"
eventEndTime: "2017-10-04T20:00"
eventPlaceCoordinates: "46.494439, 11.346764"
mapCenterCoordinates: "46.4944386, 11.3445752"
mapMobileCenterCoordinates: "46.4944386, 11.3445752"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "conferencehall.jpg"
venueSmallImage1: "catering_1.jpg"
venueSmallImage2: "catering_2.jpg"
venueTitle: "Conference Hall"
venueFeatures: ["Two video projectors", "Full set of different microphones", "State-of-the-art room for events with up to 100 participants"]

# Tweets Feed Block
#tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "cmccorpora17"
twitterFeed: "https://cmc-corpora2017.eurac.edu/tweetledee/searchjson.php?c=10&cache_interval=8000&q=%23cmccorpora%20OR%20%23cmc_corpora%20OR%20%23cmccorpora2017%20OR%20%23cmccorpora17%20OR%20%23cmccorpora16"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

    ## Tickets Block
    #ticketsTitle: "Pricetable"
    #ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
    #ticketsOffers:
    # -
    #  name: "Early Bird"
    #  price: "350"
    #  priceCurrency: "UAH"
    #  ticketsNumber: "150"
    #  ribbon: "-5%"
    #  buyButtonLink: "http://dfua.ticketforevent.com/"
    #  buyButtonText: "Buy Now"
    #  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
    #  validFrom: "2014-08-25T10:00"
    #  validThrough: "2014-09-30T23:59"
    # -
    #  name: "Last Chance"
    #  price: "450"
    #  priceCurrency: "UAH"
    #  ticketsNumber: "100"
    #  ribbon: "-20%"
    #  featured: true
    #  buyButtonLink: "http://dfua.ticketforevent.com/"
    #  buyButtonText: "Buy Now"
    #  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
    #  validFrom: "2014-10-01T00:00"
    #  validThrough: "2014-10-23T23:59"
    #  disabled: true
    # -
    #  name: "Student"
    #  price: "200"
    #  priceCurrency: "UAH"
    #  ticketsNumber: "50"
    #  buyButtonLink: "http://dfua.ticketforevent.com/"
    #  buyButtonText: "Buy Now"
    #  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
    #  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
    #  validFrom: "2014-08-20T10:00"
    #  validThrough: "2014-10-23T23:59"
    #  soldOut: true
    #  soldOutText: "Sold Out"

# Footer
socialLinks:
 # - {link: "https://twitter.com/search?l=&q=%23cmccorpora%20OR%20%23cmccorpora2016%20OR%20%23cmccorpora2017&src=typd", icon: "twitter"}
 - {link: "https://twitter.com/cmc_corpora", icon: "twitter"}
 - {link: "https://www.facebook.com/cmccorpora", icon: "facebook"}
 - {link: "https://groups.google.com/forum/?hl=de#!forum/cmc-corpora", icon: "google-groups"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {permalink: "/cfp/", text: "Call for Papers (Monograph)"}
   - {permalink: "/twitter-moment/", text: "Twitter Moment"}
   - {permalink: "/proceedings/", text: "Proceedings"}
   - {permalink: "/venue/", text: "Venue"}
   - {permalink: "/registration/", text: "Registration"}
   - {permalink: "/speakers/", text: "Accepted Papers (Conference)"}
   - {permalink: "/authors_proceedings/", text: "For Authors (Proceedings)"}
   - {permalink: "/cfp_proceedings/", text: "Call for Papers (Proceedings)"}
   - {link: "mailto:cmc-corpora2017@eurac.edu", text: "e-Mail"}
 -
  title: "&nbsp;"
  links:
   - {link: "http://cmc-corpora.org", text: "cmc-corpora conference series"}
   - {link: "http://www.eurac.edu/linguistics", text: "Institute for Applied Linguistics"}
   - {link: "http://www.eurac.edu", text: "Eurac Research"}
   - {link: "http://lcr2017.eurac.edu", text: "4th Learner Corpus Research Conference (LCR2017)"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: ""

# Speakers List Block
showSessions: false

# Team Block
teamBlockTitle: "About us"
aboutUs: "Team Block - about us"

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "venue.jpg"
directionDetailsTitle: "Conference Venue and Transportation"
directionDetailsCards:
 - {title: "Accommodation", information: '
   <p>Are you looking for a hotel in Bolzano? Please contact our <a
   href="#partnerhotels" target="_blank">partner hotels</a>. They offer special
   rates and a good service. To claim the special rates please indicate the
   conference name "cmc-corpora 2017" when booking your room.</p>
   <p>For other accommodation in Bolzano visit the official <a
   href="http://www.bolzano-bozen.it/en/accommodation-bolzano.htm"
   target="_blank">Tourist board</a>.</p>
   <p>Students can find budget accommodation with <a
   href="https://www.airbnb.com/s/Bolzano--Province-of-Bolzano-~-South-Tyrol--Italy?guests=1&checkin=&checkout=&ss_id=hsfdif78&source=bb&s_tag=EsLn-TPK"
   target="_blank">Airbnb</a>.</p>
   <p>For more rural accommodation, for example if you like to stay for farm
   holidays in South Tyrol, please have a look at <a
   href="http://www.redrooster.it/en/" target="_blank">Red Rooster: Farm
     Holidays</a>.</p>'}
 - {title: "Getting here by Train", information: '
   <p>One of the best ways to get to Bolzano is by train:
     the station of Bolzano is near the city centre and <a href="https://www.google.it/maps/dir/EURAC+Research,+Viale+Druso+Drususallee,+1,+39100+Bolzano+BZ/Bolzano+Bozen,+Bolzano,+Province+of+Bolzano+-+South+Tyrol/@46.4953347,11.3503426,17z/data=!3m1!4b1!4m13!4m12!1m5!1m1!1s0x47829c202aabf925:0x88091ac142a2771!2m2!1d11.3467639!2d46.4944386!1m5!1m1!1s0x47829e776ce75d2d:0xfe4e2377de5b2c96!2m2!1d11.3583019!2d46.4967218">a 15-minute walk</a> away from Eurac Research.
     </p>
     <p><h5>Travelling time by train</h5>
     - Rome - Bolzano: 6 hours <br />
     - Milan - Bolzano: 3.5 hours <br />
     - Verona - Bolzano: 1.5 hours <br />
     - Venice - Bolzano: 3 hours <br />
     - Innsbruck - Bolzano: 2 hours <br />
     - Munich - Bolzano: 4 hours <br />
     </p>
     '}
 - {title: "Getting here by Plane", information: '
   
   <p>The nearest international airports are in Innsbruck in the North and
   in Verona in the South. The other airports in Munich, Milano, Venice, Bologna, Bergamo, Treviso
   are over 200km away (>3h by car and >4 hours by train or shuttle bus).</p>

   <p><h5><a href="http://www.aeroportoverona.it/en/">
     Verona Airport (Villafranca)
   </a></h5>

   1 1/2 hours by car <br />
   1 hour and 45 minutes by shuttle bus
   - <a href="http://www.altoadigebus.com/">booking required</a><br />
   </p>


   <p><h5><a href="https://www.innsbruck-airport.com/en">
     Innsbruck Airport (Kranebitten)
   </a></h5>
   
   1 1/2 hours by car <br />
   2 hours by shuttle bus
   - <a href="http://www.altoadigebus.com/">booking required</a><br />
   </p>

   <p><h5><a href="http://www.munich-airport.de/en/">
     Munich Airport (Franz Josef Strauß)
   </a></h5>

   3 1/2 hours by car <br />
   4 hours by shuttle bus
   - <a href="http://www.altoadigebus.com/">booking required</a><br />
   </p>


   <p><h5><h5><a href="http://www.altoadigebus.com/">Shuttle Bus</a></h5>
   A shuttle bus service connects all major airports to the city. Please note
   that booking is mandatory.
   </p>
   '}
directionDetailsWideCards:
 -
  title: "Travel Links"
  subCards:
   -
    title: 'Our <a name="partnerhotels">Partner Hotels</a>'
    links:
     - {link: "http://www.laurin.it/en/", text: "Parkhotel Laurin ****S"}
     - {link: "http://www.greif.it/en/", text: "Hotel Greif ****"}
     - {link: "http://www.hotel-luna.it/en/welcome-1.html", text: "Parkhotel Luna Mondschein ****"}
     - {link: "http://www.scalahot.com/en/index", text: "Hotel Scala Stiegl ****"}
     - {link: "http://www.fourpointsbolzano.com/", text: "Hotel Four Points by Sheraton Bolzano ****"}
     - {link: "http://www.hotelfierabz.com/", text: "Hotel Fiera ***"}
     - {link: "http://www.hotel-post-gries.com/en/", text: "Hotel Post Gries ***"}
   - 
    title: 'Airports'
    links:
      - {link: "http://www.aeroportoverona.it/en/", text: "Verona (Villafranca)"}
      - {link: "https://www.innsbruck-airport.com/en", text: "Innsbruck (Kranebitten)"}
      - {link: "http://www.munich-airport.de/en/", text: "Munich (Franz Josef Strauß)"}
      - {link: "http://www.milanomalpensa-airport.com/en", text: "Milan (Malpensa)"}
      - {link: "http://www.veniceairport.it/en/", text: "Venice (Marco Polo)"}
      - {link: "http://www.bologna-airport.it/en/", text: "Bologna (G. Marconi)"}
      - {link: "http://www.trevisoairport.it/en/", text: "Treviso Airport"}
      - {link: "http://www.bergamoairport.co.uk/", text: "Bergamo Airport"}
   -
    title: '&nbsp;'
    links:
      - {link: "https://www.bahn.com/en/", text: "DB (German railway company)"}
      - {link: "https://www.oebb.at/en/", text: "ÖBB (Austrian railway comapny)"}
      - {link: "http://www.trenitalia.com/tcom-en/", text: "Trenitalia (Italian railway comapny)"}
      - {link: "https://www.google.it/flights/#search;f=;t=VRN,INN,MUC;d=2017-10-02;", text: "Google Flights"}
      - {link: "http://www.bolzano-bozen.it/images/pdf/How-to-reach-South-Tyrol-2015.pdf", text: "Getting here information from the Tourist board"}
